parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_name: symonfytest
  database_user: root
  database_password: root
  mailer_transport: smtp
  mailer_host: localhost
  mailer_user: ""
  mailer_password: ""
  locale: de
  secret: 8b74b69bfc4398d1b70a40bbe63703b1209ff852
